### ISSUE TITLE
Wrong state parameter handling

### ISSUE THREAD

**Issue by bsdnomad** [adamwathan/eloquent-oauth-l5#18] opened 2015-09-11 15:18 UTC
What is returned looks like:

<code>/google/login?state=mWhYA2x84XXFqn54MAdJBqCEnwKbSWNG&code=4/d2YkPDB2NCddcF5u9YqZGqpaI35JGQNRnQs9ZK-fJ3A#</code>

Seems 'state' parameter has not been handled properly because I get:

<code>InvalidAuthorizationCodeException in SocialNorm.php line 52:
...
</code>

**Update:**

Actually it could be a kind of forgery attack simulation, because Google does not accept non-public return URLs and I'm obliged to 'fake' it with a public one stored in hosts file.

**Comment by adamwathan** [comment] 2015-09-13 13:49
Were you able to resolve this? Testing locally with the Google provider and still working here :(

**Comment by bsdnomad** [comment] 2015-09-14 07:48
What is interesting it does the same with GitHub and LinkedIn, only Facebook works properly.
I guess it's about domain 'cloaking' or inability to access it from outside for some of the providers.

Really strange, I followed strictly the instructions you present in the [video](https://vimeo.com/120085196). Going to post updates if I manage to solve it.

**Comment by adamwathan** [comment] 2016-01-19 14:14
Closing for now, if you find a way to reliably reproduce or have more information please open another issue :+1:

**Closed as completed by adamwathan** 2016-01-19 14:14 UTC

**Comment by timkrins** [comment] 2016-02-03 16:31
I was having this issue - I'm only just starting with Laravel.

Figured it out - it was because my authentication routes were outside of the **web middleware**.

...which of course, I could have found out if I just googled more... gah... Mentioned at the end of issue #32

Anyhow, setting up my routes like this fixed the problem:

```
Route::group(['middleware' => ['web']], function () {

    // Redirect for authorization
    Route::get('auth/linkedin', function() {
        return SocialAuth::authorize('linkedin');
    });

    // Redirects here after authorization
    Route::get('auth/linkedin/callback', function() {

        // Log in existing users or create
        SocialAuth::login('linkedin');

        // Now have user
        $user = Auth::user();

        return Redirect::intended();
    });

});
```

**Comment by nclaveras** [comment] 2016-02-17 14:02
It happened the same to me, working locally. What worked for me was:
php artisan config:clear
but then it happened again later and I need to do the same but closing session in google/facebook/others, closing firefox and worked again.
It seems that detect you tried so many attempts and stops working.
